// [LAYER: CORE]
/**
 * Canonical Spider agent-ergonomics surface — both GraphCapability.spider and AuditCapability.spider
 * must expose these methods for alternate-entry parity.
 */
export const SPIDER_AGENT_ERGONOMICS_METHODS = [
  'audit',
  'gate',
  'gateBundle',
  'check',
  'checkAndRespond',
  'runCheckPipeline',
  'runAgentScenario',
  'bundle',
  'validateBundle',
  'batchPreflight',
  'preflight',
  'preflightBundle',
  'setBaseline',
  'compareBaseline',
  'compareBaselineBundle',
  'sessionDelta',
  'shouldProceed',
  'toolSchema',
  'outputSchema',
  'handoff',
  'handoffFromCheck',
  'buildCiArtifacts',
  'writeCiArtifacts',
  'serializeBundle',
  'parseBundleWire',
  'validateWire',
  'validateWireRestore',
  'restoreFromWire',
  'getWireOutputSchema',
  'parseNdjsonStream',
  'formatWireDigest',
  'formatCheckDigest',
  'formatPreflightDigest',
  'toCheckResponse',
  'getCheckOutputSchema',
  'getCheckInputSchema',
  'getPipelineInputSchema',
  'getSchemaRegistry',
  'normalizeCheckRequest',
  'getAgentScenarios',
  'recommendCheckRequest',
  'formatAgentDecisionGuide',
  'getWorkflowPresets',
  'safeValidateCheckRequest',
  'validateCheckPipelineRequest',
  'safeValidateCheckPipelineRequest',
  'prepareSarifUpload',
  'buildDiagnosticSummary',
  'validateCheck',
  'assertCheckPassed',
  'toCheckNdjsonStream',
  'toGithubCheckRun',
  'getProblemMatcherConfig',
  'getAgentToolkitCatalog',
  'formatCatalogPrompt',
  'getAgentRunbook',
  'getMcpToolNames',
  'validateCheckRequest',
  'getGatePolicyPresets',
  'toStructuredTelemetry',
  'agentContext',
  'applyBundleBudget',
  'compact',
  'toSarif',
  'toLspDiagnostics',
  'toDiagnosticJson',
  'toGithubAnnotations',
  'toTap',
  'toJUnitXml',
  'toNdjson',
  'formatDiffNarrative',
  'diffSinceLast',
  'diff',
  'explain',
  'explainForAgent',
  'formatNarrative',
  'resync',
] as const;

export type SpiderAgentErgonomicsMethod = (typeof SPIDER_AGENT_ERGONOMICS_METHODS)[number];

/** Graph-only structural ops — not required on AuditCapability.spider. */
export const SPIDER_GRAPH_ONLY_METHODS = [
  'bootstrapGraph',
  'applyChanges',
  'auditStructure',
  'verifyGraphIntegrity',
  'getStudyPack',
] as const;
