import * as fs from "fs"
import minimatch from "minimatch"
import * as path from "path"
import { CallExpression, ImportDeclaration, Project, SyntaxKind } from "ts-morph"
import { SovereignPolicy } from "../core/policy/SovereignPolicy"

export type Layer = "domain" | "core" | "infrastructure" | "plumbing" | "ui"

export enum CommentStyle {
	JSDOC = "jsdoc", // /** [LAYER: TYPE] */
	SLASH = "slash", // // [LAYER: TYPE]
	HASH = "hash", // # [LAYER: TYPE]
	DASH = "dash", // -- [LAYER: TYPE]
	HTML = "html", // <!-- [LAYER: TYPE] -->
}

const STYLE_REGISTRY: Record<string, CommentStyle> = {
	".ts": CommentStyle.JSDOC,
	".tsx": CommentStyle.JSDOC,
	".js": CommentStyle.JSDOC,
	".jsx": CommentStyle.JSDOC,
	".java": CommentStyle.JSDOC,
	".go": CommentStyle.SLASH,
	".rs": CommentStyle.SLASH,
	".proto": CommentStyle.SLASH,
	".grit": CommentStyle.SLASH,
	".cpp": CommentStyle.SLASH,
	".c": CommentStyle.SLASH,
	".h": CommentStyle.SLASH,
	".sh": CommentStyle.HASH,
	".py": CommentStyle.HASH,
	".rb": CommentStyle.HASH,
	".yaml": CommentStyle.HASH,
	".yml": CommentStyle.HASH,
	".env": CommentStyle.HASH,
	".dockerfile": CommentStyle.HASH,
	".sql": CommentStyle.DASH,
	".hs": CommentStyle.DASH,
	".lua": CommentStyle.DASH,
	".md": CommentStyle.HTML,
	".html": CommentStyle.HTML,
	".xml": CommentStyle.HTML,
	".vue": CommentStyle.HTML,
	".svelte": CommentStyle.HTML,
}

const STRICT_BLOCKLIST = [
	".json",
	".json5",
	".lock",
	".sum",
	".bin",
	".exe",
	".iso",
	".png",
	".jpg",
	".jpeg",
	".gif",
	".svg",
	".ico",
	".woff",
	".woff2",
	".ttf",
	".eot",
]

/**
 * Determines the layer of a given file path based on Joy-Zoning conventions or spider.spec.json.
 */
export function getLayer(filePath: string): Layer {
	const normalized = filePath.replace(/\\/g, "/")

	// Try to load spider.spec.json for custom domain/layer mappings
	try {
		const specPath = path.resolve(process.cwd(), "spider.spec.json")
		if (fs.existsSync(specPath)) {
			const spec = JSON.parse(fs.readFileSync(specPath, "utf-8"))
			if (spec.resources) {
				// Check if any resource path matches
				for (const [_key, resource] of Object.entries(spec.resources)) {
					const res = resource as { path?: string; domain?: string }
					if (res.path && normalized.includes(res.path)) {
						if (res.domain) {
							const domainToLayer: Record<string, Layer> = {
								ui: "ui",
								api: "infrastructure",
								admin: "infrastructure",
								domain: "domain",
								core: "core",
							}
							return domainToLayer[res.domain] || "infrastructure"
						}
					}
				}
			}
		}
	} catch (_e) {
		// Fallback to default logic
	}

	if (normalized.includes("src/domain/")) return "domain"
	if (normalized.includes("src/infrastructure/")) return "infrastructure"
	if (normalized.includes("src/plumbing/")) return "plumbing"
	if (normalized.includes("src/ui/")) return "ui"

	// Fallback for DietCode's specific structure if it doesn't match the standard Joy-Zoning
	// NOTE: src/core/ is NOT strict domain — it's a "soft" domain with relaxed enforcement
	if (normalized.includes("src/core/")) return "core"
	if (normalized.includes("src/services/") || normalized.includes("src/integrations/")) return "infrastructure"
	if (normalized.includes("src/utils/")) return "plumbing"
	if (normalized.includes("webview-ui/")) return "ui"

	return "infrastructure" // Default
}

/**
 * Determines if a file supports architectural [LAYER: TYPE] tags.
 * Only source files that support JSDoc-style comments are included.
 */
export function isLayerTagSupported(filePath: string, content?: string): boolean {
	const ext = path.extname(filePath).toLowerCase()
	if (filePath.toLowerCase().endsWith(".d.ts") || STRICT_BLOCKLIST.includes(ext)) return false

	const policy = SovereignPolicy.getInstance(process.cwd())
	const config = policy.getGlobalConfig()
	const supportedExtensions = config.supportedLayerTags
	const excludePaths = config.excludePaths || []

	// 1. Path-based Glob Exclusion
	for (const pattern of excludePaths) {
		if (
			minimatch(filePath, pattern, { dot: true }) ||
			minimatch(path.relative(process.cwd(), filePath), pattern, { dot: true })
		) {
			return false
		}
	}

	// 2. Extension Check
	const style = STYLE_REGISTRY[ext]
	const isExtSupported = supportedExtensions && supportedExtensions.length > 0 ? supportedExtensions.includes(ext) : !!style

	if (!isExtSupported || !style) return false

	// 3. Content-based Protection (if content is provided)
	if (content) {
		// Empty check
		if (content.trim().length === 0) return false

		// Binary check (search for null bytes in first 1KB)
		const sample = content.slice(0, 1024)
		if (sample.includes("\0")) return false

		// Generated check
		const generatedMarkers = ["@generated", "Code generated by", "DO NOT EDIT", "Automatically generated"]
		if (generatedMarkers.some((marker) => content.slice(0, 5000).includes(marker))) {
			return false
		}
	}

	return true
}

/**
 * Generates the appropriate layer comment for the given file and layer.
 * Detects shebangs and respects language-specific comment syntax.
 * Now performs in-place replacement if a tag already exists.
 */
export function generateLayerComment(filePath: string, layer: string, content?: string): string | null {
	if (!isLayerTagSupported(filePath, content)) return null

	const ext = path.extname(filePath).toLowerCase()
	const style = STYLE_REGISTRY[ext]
	if (!style) return null

	const tag = layer.toUpperCase()
	const label = `[LAYER: ${tag}]`
	let comment = ""

	switch (style) {
		case CommentStyle.JSDOC:
			comment = `/**\n * ${label}\n */\n\n`
			break
		case CommentStyle.SLASH:
			comment = `// ${label}\n\n`
			break
		case CommentStyle.HASH:
			comment = `# ${label}\n\n`
			break
		case CommentStyle.DASH:
			comment = `-- ${label}\n\n`
			break
		case CommentStyle.HTML:
			comment = `<!-- ${label} -->\n\n`
			break
	}

	if (content) {
		// 1. In-place Replacement Strategy
		const tagRegex = /\[LAYER:\s*(DOMAIN|CORE|INFRASTRUCTURE|PLUMBING|UI|UTILS)\]/i
		const existingMatch = content.slice(0, 10000).match(tagRegex)

		if (existingMatch) {
			// Find the line containing the tag and replace Just the tag part
			// This preserves the existing comment style if possible
			return content.replace(tagRegex, label)
		}

		// 2. Structural Header Detection (Shebang + Frontmatter)
		let injectionIndex = 0

		// Check for Shebang (must be at the very start)
		if (content.startsWith("#!")) {
			const firstLineEnd = content.indexOf("\n")
			if (firstLineEnd !== -1) {
				injectionIndex = firstLineEnd + 1
			}
		}

		// Check for YAML Frontmatter (starts after Shebang if exists, or at 0)
		const remainingFromIndex = content.slice(injectionIndex)
		const frontmatterMatch = remainingFromIndex.match(/^---\n([\s\S]*?)\n---\n?/)
		if (frontmatterMatch) {
			injectionIndex += frontmatterMatch[0].length
		}

		if (injectionIndex > 0) {
			const header = content.slice(0, injectionIndex)
			const body = content.slice(injectionIndex)
			return `${header}${comment}${body}`
		}

		return `${comment}${content}`
	}

	return comment
}

/**
 * Validates architectural smells in the given content.
 * Layer-aware: strict checks apply only to domain/infrastructure.
 */
export function validateSmells(filePath: string, content: string): string[] {
	const errors: string[] = []
	const layer = getLayer(filePath)

	// Multiple classes in a single file — only enforced in domain
	if (layer === "domain") {
		const classCount = (content.match(/class\s+/g) || []).length
		if (classCount > 1) {
			errors.push(`${path.basename(filePath)}: Multiple classes in a single file — split into separate files.`)
		}
	}

	// Discouraged 'any' type — domain and infrastructure only (core is exempt)
	if (layer === "domain" || layer === "infrastructure") {
		if (content.includes(": any") || content.includes("<any>")) {
			// Surface as an architectural smell rather than a strict error
			errors.push(`${path.basename(filePath)}: Architectural smell — 'any' type detected.`)
		}
	}

	return errors
}

/**
 * Validates layering constraints using AST analysis.
 */
export function validateLayering(filePath: string, content: string): string[] {
	const errors: string[] = []
	const layer = getLayer(filePath)

	const project = new Project()
	const sourceFile = project.createSourceFile(filePath, content, { overwrite: true })

	// Validate imports
	sourceFile.getImportDeclarations().forEach((imp: ImportDeclaration) => {
		const moduleSpecifier = imp.getModuleSpecifierValue()
		if (moduleSpecifier.startsWith(".")) {
			const absoluteImportPath = path.resolve(path.dirname(filePath), moduleSpecifier)
			const importedLayer = getLayer(absoluteImportPath)

			if (layer === "domain") {
				if (importedLayer === "infrastructure" || importedLayer === "ui") {
					errors.push(`Domain layer in ${path.basename(filePath)} cannot import from ${importedLayer}.`)
				}
			}
			if (layer === "core") {
				if (importedLayer === "ui") {
					errors.push(`Core layer in ${path.basename(filePath)} cannot import from UI — use events or callbacks.`)
				}
			}
			if (layer === "infrastructure") {
				if (importedLayer === "ui") {
					errors.push(`Infrastructure layer in ${path.basename(filePath)} cannot import from UI.`)
				}
			}
			if (layer === "ui") {
				if (importedLayer === "infrastructure") {
					errors.push(`UI layer in ${path.basename(filePath)} cannot directly import Infrastructure.`)
				}
			}
			if (layer === "plumbing") {
				if (["domain", "core", "infrastructure", "ui"].includes(importedLayer)) {
					errors.push(`Plumbing layer in ${path.basename(filePath)} cannot depend on ${importedLayer} layer.`)
				}
			}
		}
	})

	// Validate forbidden calls in Domain
	if (layer === "domain") {
		const forbiddenTerms = ["fetch", "fs.", "child_process", "axios", "http."]
		sourceFile.getDescendantsOfKind(SyntaxKind.CallExpression).forEach((call: CallExpression) => {
			const text = call.getExpression().getText()
			if (forbiddenTerms.some((term) => text.includes(term))) {
				errors.push(`Architectural Violation: Forbidden call '${text}' in Domain layer file ${path.basename(filePath)}.`)
			}
		})
	}

	// Circular Dependency Detection (Surface Level: A ↔ B direct cycles)
	sourceFile.getImportDeclarations().forEach((imp: ImportDeclaration) => {
		const moduleSpecifier = imp.getModuleSpecifierValue()
		if (moduleSpecifier.startsWith(".")) {
			const resolvedPath = path.resolve(
				path.dirname(filePath),
				moduleSpecifier + (moduleSpecifier.endsWith(".ts") ? "" : ".ts"),
			)
			try {
				const importedFile = project.addSourceFileAtPathIfExists(resolvedPath)
				if (importedFile) {
					const isCircular = importedFile.getImportDeclarations().some((i) => {
						const spec = i.getModuleSpecifierValue()
						if (!spec.startsWith(".")) return false
						const backResolved = path.resolve(path.dirname(resolvedPath), spec + (spec.endsWith(".ts") ? "" : ".ts"))
						return backResolved === filePath
					})
					if (isCircular) {
						errors.push(
							`Architectural Violation: Circular dependency detected between ${path.basename(filePath)} and ${path.basename(resolvedPath)}.`,
						)
					}
				}
			} catch {
				/* Imported file not on disk or inaccessible; skip circular check for this import */
			}
		}
	})

	return errors
}

/**
 * Parses the [LAYER: TYPE] tag from the file content.
 * Follows the Header Rule: tag must be within the first 10,000 characters.
 */
export function parseLayerTag(content: string): Layer | null {
	const header = content.slice(0, 10000)
	const match = header.match(/\[LAYER:\s*(DOMAIN|CORE|INFRASTRUCTURE|PLUMBING|UI|UTILS)\]/i)
	if (!match) return null

	const tag = match[1].toLowerCase()
	if (tag === "utils") return "plumbing"
	return tag as Layer
}

/**
 * Validates the vertical depth of relative imports.
 * Limit: 3 levels of relative depth (../../..).
 */
export function validateImportDepth(filePath: string, content: string): string[] {
	const errors: string[] = []
	const lines = content.split("\n")

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i]
		if (line.includes('from "') || line.includes("from '")) {
			const match = line.match(/["'](\.\.\/)+[^"']*["']/)
			if (match) {
				const depth = (match[0].match(/\.\.\//g) || []).length
				if (depth > 3) {
					errors.push(
						`${path.basename(filePath)}:${i + 1}: Excessive relative navigation (${depth} levels) — use @ aliases or flatten structure.`,
					)
				}
			}
		}
	}

	return errors
}

/**
 * Full Joy-Zoning validation for a file.
 */
export function validateJoyZoning(filePath: string, content: string): { success: boolean; errors: string[] } {
	const allErrors: string[] = []

	// 1. Tag Locality & PGA (Principle of Geographic Alignment)
	const tag = parseLayerTag(content)
	const pathLayer = getLayer(filePath)

	if (!tag) {
		if (isLayerTagSupported(filePath)) {
			allErrors.push(`${path.basename(filePath)}: Missing mandatory [LAYER: TYPE] header tag.`)
		}
	} else if (tag !== pathLayer) {
		allErrors.push(
			`${path.basename(filePath)}: Geographic Misalignment — Tag [LAYER: ${tag.toUpperCase()}] does not match path layer '${pathLayer}'.`,
		)
	}

	// 2. Import Depth
	const depthErrors = validateImportDepth(filePath, content)
	allErrors.push(...depthErrors)

	// 3. Smells & Layering
	const smellErrors = validateSmells(filePath, content)
	const layeringErrors = validateLayering(filePath, content)
	allErrors.push(...smellErrors, ...layeringErrors)

	return {
		success: allErrors.length === 0,
		errors: allErrors,
	}
}

/**
 * Analyzes code content and suggests which architectural layer best fits.
 * Returns the suggested layer and the reasoning behind the suggestion.
 */
export function suggestLayerForContent(content: string): { layer: Layer; reason: string } | null {
	// Check for UI patterns
	if (/import\s+.*from\s+["']react/i.test(content) || /jsx|tsx|component|render/i.test(content)) {
		return { layer: "ui", reason: "Contains React/JSX patterns — belongs in the UI layer." }
	}

	// Check for I/O / adapter patterns
	if (/import\s+.*from\s+["'](?:fs|http|https|net|child_process|pg|mysql|redis|axios)/i.test(content)) {
		return { layer: "infrastructure", reason: "Contains I/O or external service imports — belongs in Infrastructure." }
	}

	// Check for pure utility patterns (no class, stateless exports)
	if (
		!/class\s+/.test(content) &&
		/export\s+(?:function|const)\s+/.test(content) &&
		!/import\s+.*from\s+["']@(?:core|infrastructure|services)/.test(content)
	) {
		return { layer: "plumbing", reason: "Stateless utility functions with no layer dependencies — fits Plumbing." }
	}

	return null // can't confidently suggest
}

/**
 * Extracts a target file path from various common tool parameter names.
 */
export function getTargetPath(params: Record<string, unknown>): string | null {
	if (!params) return null
	const rawPath = params.path || params.file_path || params.target_file || params.absolutePath
	if (typeof rawPath !== "string") return null
	return rawPath
}
